### ISSUE TITLE
Fractional Coordinates in 2169

### ISSUE THREAD

**Issue by KenDickey** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#37]
Loading and opening a ColorEditor generates a fractional coordinate which causes draw failure in color slider.

**Comment by KenDickey** [comment]
Easy way to see this bug is to select a new ImageMorph via the World Menu:
  World> NewMorph
     Basic> Imagrmorph

Method BitBlt>>copyBits finds a fractional coordinate and chokes.

**Comment by jvuletich** [comment]
In ImageMorph, the problem is not a fractional coordinate, but the use of the old and now unsupported hibernated Form format. Today, disk and RAM are cheaper than CPU, so compressing in-memory Forms doesn't make much sense anymore. So, I removed Form hibernation.
Please see update 2198, where I fixed ImageMorph to use some supported format, like JPEG or BMP. Please update your code accordingly.
Afterwards, if you are satisfied with the results, please close this issue.

**Comment by KenDickey** [comment]
2198 fixes the symptom for ImageMorph, but the original problem remained.

I updated ColorSliderMorph>>scaledZPosition to rounds its result.

This cures the symptom for the ColorEditor slider, but I suspect someone else will trip over this one.

**Comment by jvuletich** [comment]
Thanks. This is a completely unrelated issue. It is fixed in update #2202.

**Comment by KenDickey** [comment]
Fix verified in 2203.

Thanks a bunch !!!
